{% set version = "0.4.0" %}

package:
  name: recommonmark
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/recommonmark/recommonmark-{{ version }}.tar.gz
  sha256: 6e29c723abcf5533842376d87c4589e62923ecb6002a8e059eb608345ddaff9d

build:
  number: 2
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - cm2html = recommonmark.scripts:cm2html
    - cm2latex = recommonmark.scripts:cm2latex
    - cm2man = recommonmark.scripts:cm2man
    - cm2pseudoxml = recommonmark.scripts:cm2pseudoxml
    - cm2xetex = recommonmark.scripts:cm2xetex
    - cm2xml = recommonmark.scripts:cm2xml

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - commonmark <=0.5.4
    - docutils >=0.11

test:
  imports:
    - recommonmark
  commands:
    - cm2html -h
    - cm2latex -h
    - cm2man -h
    - cm2pseudoxml -h
    - cm2xetex = -h
    - cm2xml = -h
about:
  home: https://github.com/rtfd/recommonmark
  license: MIT
  license_family: MIT
  license_file: license.md
  summary: 'A docutils-compatibility bridge to CommonMark'

  description: |
    A docutils-compatibility bridge to CommonMark.
    This allows you to write CommonMark inside of Docutils & Sphinx projects.
  doc_url: http://recommonmark.readthedocs.org
  dev_url: https://github.com/rtfd/recommonmark

extra:
  recipe-maintainers:
    - CJ-Wright
    - ocefpaf
