travis:
  secure:
    BINSTAR_TOKEN: 4WgAXjhtLJHlr280ZfuA9mAxgIHQCwlkfE4vsw0XbetPXMS/LEbxJkGfyRNv81aPsZLsdSMbuZn37FeuASjvwIu0vOLmHGp26t51g4UK8Q7WF6Ej5HcAK9hVqxFLuMonGQLVZ7oxSh3ghlMxDEoYXXne3NUQWWY1kbaEZYeRg9xg0hrroLJWkxT2bwbwcS8dDyyj3UnBVvaG6AmbtY2ayBulJRP3RMqiKQpVbEoPGQcpbd8VrP6/lRjZEzkP71Riap3yyCQbZdmFDLZIy5IOZVbljNuqse4tASnmsJQbyRVGD0HoD5xalNBMpLiQTOGTRfHg//by4+PpU8gKP2lJjdKiNGwrIpLe/+0qnNGs/bWtxBz1gZA3Q1DdYfEF9WFfqJrXDL3Th8gLfyQLPjA5V2sHKNOh0hwQ/gJsASU73rrjK3Sif56Cfl11/yiuz4DxoJpamD9ognX3wG8hgWjrgZiQjIIBeht0gvct2YpbtLV6HO9Ma0Mi6Qz/bpJiz5K2yRx24AqDsegyUjecyL9mn2tzTqtWCd1wcLsXKrHxe44MfAjsJMtatsd41pDUJiI6JbkJi9qTuCRsKh54dFocIwJ6RZs4Avxr8HYe8UQxM4J3Iw5+fDSDDGgeodX4ElRgpD9vz4Lcefpsw+3G1OtVO9uhPhzIV//7WtGpA49ZXvI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
