travis:
  secure:
    BINSTAR_TOKEN: TJx4f0fOeV8MxbTUfM1E+sSdiQa3xxi5Gl8RYmEY+6K5bORf8hEtg1awmKdWq46SPYGvwr1jKxB9abtZJUMDWQOTMhfmxI4+cEO3lTA6Litb2gqcW4KO6wKvQckYEKC/oABXDwS2HLJ1owAKWjaDFWxuotKSp1ROLajh1IIik6rmdyRS6JmrbMHWjOnyNPI2RxRL0eO0goJTNBRNLy+YExYutw++iMA6MuPgMS8hNai+htam5OnLA3/9/H6e9r1vCcI+sO17YXR+2pYdwDF2dk4XuE+5iV4d7lsJHFHHVQkf6bcLQiR+f4Chw739MpeRxbcJ1GDDLfm+qs1ncPLmcvT7f/yHrSVNigOdPszwRL4Oq+BJ+L1up6y7Sx1JYO4u/VUs26iXVmdvclUcSiO23RYci+Bk7cfYiDWYu+xF7quB+fIoB+OH7DJ8Zr9JNS7oCKpiYSpHcgCP9VtRco6/zWZrsfgNHODIogguHaelOGTmuIZgusLqNIQb7RM44WBclAXqVP2GiCzoIv3AMHSFyaOFqeF68nF8FeDvyXS6nrBkrWp1HjsB6ueFGuV1oORyiBiCam3LkhPDJAWgpFEjJoYMSnD+AAYPdrvErJmx4f+Va+hYXFzJ1BLFQ8jZ98VGaznuTqU2GU4QtjGCaaLFfLF0RN+KWFLiMNyJps58fY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
